PersonalBlog/Models/AddOrUpdatePostModel.cs
using System;
using PersonalBlog.Entities;
using PersonalBlog.Logic.Managers;

namespace PersonalBlog.Models
{
    public class AddOrUpdatePostModel
    {
        public int? PostId { get; set; }

        public string Source { get; set; }

        public string Title { get; set; }

		public bool UpdateCreationDate { get; set; }

        public PostDto ToPostDto()
        {
            var postProcessResult = PostManager.ProcessSource(Source);
            DateTime nowTime = DateTime.Now;

            var result = new PostDto
            {
                Title = Title,
                CreationDate = nowTime,
                UpdationDate = nowTime,
                PreviewEndIndex = postProcessResult.PreviewEndIndex,
                Source = postProcessResult.CleanedSource
            };

            if (PostId.HasValue)
                result.PostId = PostId.Value;
            
            return result;
        }

	    public void UpdatePostDto(PostDto existentPost)
	    {
		    var postProcessResult = PostManager.ProcessSource(Source);

		    existentPost.Title = Title;
			existentPost.Source = postProcessResult.CleanedSource;
		    existentPost.PreviewEndIndex = postProcessResult.PreviewEndIndex;

			existentPost.UpdationDate = DateTime.Now;
			if (UpdateCreationDate)
				existentPost.CreationDate = DateTime.Now;
		}
    }
}

PersonalBlog/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PersonalBlog.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "UserName")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}

PersonalBlog/Models/PagerModel.cs
namespace PersonalBlog.Models
{
	public class PagerModel
	{
		public string Action { get; set; }

		public string Controller { get; set; }

		public int CurrentPageIndex { get; set; }

		public int PageCount { get; set; }
	}
}

PersonalBlog/Controllers/AboutMeController.cs
using System;
using System.Web.Mvc;
using NodaTime;

namespace PersonalBlog.Controllers
{
    public class AboutMeController : Controller
    {
        //
        // GET: /AboutMe/

        public ActionResult Index()
        {
            ViewBag.AgeInYears = (int)Period.Between(
                new LocalDateTime(1995, 4, 29, 0, 0),
                LocalDateTime.FromDateTime(DateTime.Now)).Years;

            return View();
        }

    }
}

PersonalBlog/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PersonalBlog.Models;
using WebMatrix.WebData;

namespace PersonalBlog.Controllers
{
    public class AccountController : Controller
    {
        //
        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var isSuccess = WebSecurity.Login(model.UserName, model.Password, model.RememberMe);

            if (isSuccess)
                return Redirect(returnUrl);
            else
            {
                ModelState.AddModelError("", "Wrong login/password");
                return View(model);
            }
        }

    }
}

PersonalBlog/Controllers/AdminController.cs
using System.IO;
using System.Web.Mvc;
using PersonalBlog.DAL.DALs;
using PersonalBlog.DAL.Results;
using PersonalBlog.Logic.Managers;
using PersonalBlog.Models;

namespace PersonalBlog.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
	        return RedirectToAction("Posts", new { pageIndex = 1 });
        }

		public ActionResult Posts(int pageIndex)
        {
			return View(PostBaseDal.GetList(pageIndex));
        }

		public ActionResult Logs(int pageIndex)
        {
			return View(LogEntryDal.GetList(pageIndex));
        }

        public ActionResult Add()
        {
            return View("AddOrUpdatePost", new AddOrUpdatePostModel
            {
                PostId = null,
                Source = string.Empty
            });
        }

        public ActionResult Update(int postId)
        {
            var result = PostDal.Get(postId);
            if (result.ProblemType != ProblemType.NoProblem)
                return HttpNotFound();

            var post = result.Result;

            return View("AddOrUpdatePost", new AddOrUpdatePostModel
            {
                PostId = postId,
                Source = PostManager.RestoreSource(post.Source, post.PreviewEndIndex),
                Title = post.Title
            });
        }

        public ActionResult Delete(int postId)
        {
            PostDal.Delete(postId);
			//Get post title from DB too expensive for logging
			LogManager.LogPost(postId.ToString(), "Post was deleted");

			return RedirectToAction("Posts", new { pageIndex = 1 });
        }

        [HttpPost]
        public ActionResult AddOrUpdate(AddOrUpdatePostModel model)
        {
            if (model.PostId == null)
            {
                PostDal.Insert(model.ToPostDto());
				LogManager.LogPost(model.Title, "Post was added");
			}
            else
            {
	            var existentPost = PostDal.Get(model.PostId.Value);
	            if (existentPost.ProblemType != ProblemType.NoProblem)
					throw new InvalidDataException("There is no such post in data base to update!");

				model.UpdatePostDto(existentPost.Result);

                PostDal.Update(existentPost.Result);
				LogManager.LogPost(model.Title, "Post was updated");
			}

            return Content(Url.Action("Posts", new { pageIndex = 1 }));
        }
    }
}

PersonalBlog/Controllers/ElementController.cs
using System.Web.Mvc;
using PersonalBlog.Models;

namespace PersonalBlog.Controllers
{
    public class ElementController : Controller
    {
        public PartialViewResult Pager(string action, string controller, int currentPageIndex, int pageCount)
        {
            ViewBag.CurrentPageIndex = currentPageIndex;

            return PartialView(new PagerModel()
            {
	            Action = action,
				Controller = controller,
				CurrentPageIndex = currentPageIndex,
				PageCount = pageCount
            });
        }
    }
}

PersonalBlog/Controllers/HomeController.cs
using System.Web.Mvc;

namespace PersonalBlog.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Index", "PostPreviews", new { pageIndex = 1 });
        }

    }
}

PersonalBlog/Controllers/MyProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PersonalBlog.Controllers
{
    public class MyProjectsController : Controller
    {
        //
        // GET: /MyProject/

        public ActionResult Index()
        {
            return View();
        }

    }
}

PersonalBlog/Controllers/PostController.cs
using System.Web.Mvc;
using PersonalBlog.DAL.DALs;
using PersonalBlog.DAL.Results;

namespace PersonalBlog.Controllers
{
    public class PostController : Controller
    {
        public ActionResult Index(int postId)
        {
            var postResult = PostDal.Get(postId, true);

            if (postResult.ProblemType == ProblemType.NoProblem)
                return View(postResult.Result);

            return new HttpNotFoundResult();
        }
    }
}

PersonalBlog/Controllers/PostPreviewsController.cs
using System.Web.Mvc;
using PersonalBlog.DAL.DALs;

namespace PersonalBlog.Controllers
{
    public class PostPreviewsController : Controller
    {
        public ActionResult Index(int pageIndex)
        {
			return View(PostDal.GetList(pageIndex));
        }

    }
}

PersonalBlog/Views/Admin/AddOrUpdatePost.cshtml
@model PersonalBlog.Models.AddOrUpdatePostModel

@{
    ViewBag.Title = "Добавить или обновить пост";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@Styles.Render("~/Content/css/markdown-editor")

@Scripts.Render("~/bundles/markdown")
@Scripts.Render("~/bundles/markdown-editor")
@Scripts.Render("~/bundles/postManager")
@Scripts.Render("~/bundles/addOrUpdatePost")

<div class="title-wrapper">
    <label>Заголовок:</label>
    <input id="title" type="text" value="@Model.Title"/>
</div>

<textarea id="md-editor" data-post-id="@Model.PostId">@Model.Source</textarea>
<label for="update-creation-date" class="update-creation-date">
    <input type="checkbox" id="update-creation-date"/>
    Обновить дату создания
</label>

<button id="add-or-update-button" style="float: right">Добавить или обновить</button>

PersonalBlog/Views/Admin/Index.cshtml
@using PersonalBlog.Entities
@model List<PostBaseDto>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="tools-panel">
    <a class="add-new-post" href="@Url.Action("Add")">Добавить новый пост</a>
</div>

@foreach (PostBaseDto post in Model)
{
    <div class="post-item">
        <i>[@post.PostId]</i>
        <label>@post.Title</label>

        <div class="action-div">
            <a class="edit-link" href="@Url.Action("Update", new {postId = post.PostId})">редактировать</a>
            <a class="delete-link"  href="@Url.Action("Delete", new {postId = post.PostId})">удалить</a>
        </div>
    </div>
}

PersonalBlog/Views/Admin/Logs.cshtml
@using System.Globalization
@using PersonalBlog.Entities
@model PersonalBlog.DAL.Results.PageResult<LogEntryDto>

@{
    ViewBag.Title = "Логи";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@foreach (LogEntryDto log in Model.ResultList)
{
    <div class="admin-list-item">
        <b>[@log.Type.ToString()]</b>
        <i>{@log.Date.ToString(CultureInfo.InvariantCulture)}</i>
        <label>@log.Source</label>
    </div>
}

@Html.Action("Pager", "Element",
    new { action = "Logs", controller = "Admin", currentPageIndex = Model.CurrentPage, pageCount = Model.PageCount })

<script>
    $(function () {
        $("#logs").addClass("selected");
    });
</script>

PersonalBlog/Views/Admin/Posts.cshtml
@using PersonalBlog.Entities
@model PersonalBlog.DAL.Results.PageResult<PostBaseDto>

@{
    ViewBag.Title = "Посты";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="tools-panel">
    <a class="add-new-post" href="@Url.Action("Add")">Добавить новый пост</a>
</div>

@foreach (PostBaseDto post in Model.ResultList)
{
    <div class="admin-list-item">
        <i>[@post.PostId]</i>
        <label>@post.Title</label>

        <div class="action-div">
            <a class="edit-link" href="@Url.Action("Update", new {postId = post.PostId})">редактировать</a>
            <a class="delete-link"  href="@Url.Action("Delete", new {postId = post.PostId})">удалить</a>
        </div>
    </div>
}

@Html.Action("Pager", "Element",
    new { action = "Posts", controller = "Admin", currentPageIndex = Model.CurrentPage, pageCount = Model.PageCount })

<script>
    $(function () {
        $("#posts").addClass("selected");
    });
</script>

PersonalBlog/Views/Element/Pager.cshtml
@model PersonalBlog.Models.PagerModel

<div align="center" class="pager">
    @if (Model.CurrentPageIndex != 1)
    {
        <a class="move-prev" href="@Url.Action(Model.Action, Model.Controller, new { pageIndex = Model.CurrentPageIndex - 1 })">Назад</a>
    }
    <label>| Страница: @ViewBag.CurrentPageIndex |</label>
        @if (Model.CurrentPageIndex != Model.PageCount)
    {
        <a class="move-next" href="@Url.Action(Model.Action, Model.Controller, new { pageIndex = Model.CurrentPageIndex + 1 })">Вперед</a>
    }
</div>

@Styles.Render("~/Content/css/pager")

PersonalBlog/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_BlogLayout.cshtml";
}

<h2>Index</h2>

PersonalBlog/Views/MyProjects/Index.cshtml
@{
    ViewBag.Title = "Мои проекты";
    Layout = "~/Views/Shared/_BlogLayout.cshtml";
}

@Styles.Render("~/Content/css/myProjects")

<p>
    Ниже представлены те мои домашние проекты, которые заслуживают хоть какого-то внимания и могут быть
    вам интересны. Все проекты имеют открытый исходный код.
    В данный список не включены многие <a href="@Url.Action("Index", "AboutMe")">ранние проекты</a>
    (вкладка "Еще немного обо мне").
</p>

<label class="separator">Библиотеки</label>

<div class="my_project_div">
    <img src="~/Content/images/bigio-logo.png"/>
    <label>
        - это библиотека .Net коллекций для эффективной работы с миллионами и миллиардами элементов.
        Библиотека очень проста в использовании, мала и не имеет никаких зависимостей.
    </label>
    <p>
        <div class="project_info_row project_site">
            <b>Больше информации:</b> <a href="http://80levelelf.github.io/Bigio/">Сайт библиотеки</a>
        </div>
        <div class="project_info_row license">
            <b>Лицензия:</b> <a href="https://github.com/80LevelElf/Bigio/blob/master/README.txt">указана в исходном коде</a>
            <label> (BSD)</label>
        </div>
        <div class="project_info_row source-link">
            <b>Исходный код:</b> <a href="https://github.com/80LevelElf/Bigio/">GitHub</a>
        </div>
        <div class="project_info_row documentation">
            <b>Документация:</b> <a href="https://github.com/80LevelElf/Bigio/wiki">Wiki</a>
        </div>
        <div class="project_info_row tech">
            <b>Технологии:</b> <label class="blacked">C#</label>.
        </div>
    </p>
</div>

<!--
<label class="separator">Мобильные приложения(Android)</label>

<div class="my_project_div">
    <img src="~/Content/images/newochem-logo.png"/>
    <label>
        Newочем App - это мобильный клиент на Android для некоммерческого
        <a href="https://vk.com/newochem">сообщества переводчиков</a>, позволяющий читать переводы без привязки к
        ВКонтакте и добавляющий дополнительные возможности.
    </label>
    <p>
        <div class="project_info_row license">
            <b>Лицензия:</b> <a href="https://github.com/80LevelElf/NewochemApp/blob/master/LICENSE">указана в исходном коде</a>
            <label> (MIT)</label>
        </div>
        <div class="project_info_row source-link">
            <b>Исходный код:</b> <a href="https://github.com/80LevelElf/NewochemApp">GitHub</a>
        </div>
        <div class="project_info_row tech">
            <b>Технологии:</b>
            <label class="blacked">Java</label>, <label class="blacked">Android</label>, <label class="blacked">VK SDK</label>.
        </div>
    </p>
</div>
-->

<label class="separator">Сайты</label>
<div class="my_project_div">
    <b>Мой блог</b>
    <label>
        - это ... мой блог. Можно было бы взять какой-нибудь Wordpress и не думать не о чем. Но
        во-первых - с Wordpress'ом все равно пришлось бы возиться, чтобы довести его до состояния,
        которое мне нужно. А во-вторых - коли я все равно буду платить за хостинг и доменное имя, то,
        скорее всего, буду использовать этот сайт так же для нужд всех моих проектов.
    </label>
    <p>
        <div class="project_info_row license">
            <b>Лицензия:</b> <a href="https://github.com/80LevelElf/PersonalBlog/blob/master/LICENSE">указана в исходном коде</a>
            <label> (GPL)</label>
        </div>
        <div class="project_info_row source-link">
            <b>Исходный код:</b> <a href="https://github.com/80LevelElf/PersonalBlog">GitHub</a>
        </div>
        <div class="project_info_row tech">
            <b>Технологии:</b>
            <label class="blacked">C#</label>,  <label class="blacked">JavaScript</label>,  
            <label class="blacked">JQuery</label>,  <label class="blacked">JQuery UI</label>,  
            <label class="blacked">T-SQL</label>,  <label class="blacked">Linq to DB</label>.
        </div>
    </p>
</div>

<script>
    $(function () {
        $("#my-projects_ref").addClass("selected");
    });
</script>

PersonalBlog/Views/Post/Index.cshtml
@model PersonalBlog.Entities.PostDto

@{
    ViewBag.Title = @Model.Title;
    Layout = "~/Views/Shared/_BlogLayout.cshtml";
}

@Styles.Render("~/Content/css/post")
@Styles.Render("~/Content/css/highlightStyle")

@Scripts.Render("~/bundles/postManager")
@Scripts.Render("~/bundles/post")
@Scripts.Render("~/bundles/markdown")
@Scripts.Render("~/bundles/highlight")

<div class="post-wrapper">
    <div class="header">
        <label class="title">@Model.Title</label>
    </div>
    <div class="source">
        @Model.Source
    </div>
    <div class="info">
        <div class="right">
            <label class="view-count">@Model.ViewCount просмотр(ов)</label>
            <i class="added-time">(@Model.CreationDate.ToShortDateString())</i>
        </div>
    </div>
</div>

@{
    Disqus.Initialize("80levelelf");
}

@Disqus.ShowComments("post/" + Model.PostId)

PersonalBlog/Views/PostPreviews/Index.cshtml
@using PersonalBlog.Entities
@model PersonalBlog.DAL.Results.PageResult<PostDto>

@{
    ViewBag.Title = "Мои записи";
    Layout = "~/Views/Shared/_BlogLayout.cshtml";
}

@Styles.Render("~/Content/css/post-previews")
@Styles.Render("~/Content/css/highlightStyle")

@Scripts.Render("~/bundles/postManager")
@Scripts.Render("~/bundles/postPreview")
@Scripts.Render("~/bundles/markdown")
@Scripts.Render("~/bundles/highlight")

@{
    foreach (PostDto post in Model.ResultList)
    {
        <div class="post-wrapper">
            <div class="header">
                <a class="title" href="@Url.Action("Index", "Post", new {postId = post.PostId})">@post.Title</a>
            </div>
            <div class="source">
                @post.SourcePreview
            </div>
            <div class="info">
                <a class="to-detail" href="@Url.Action("Index", "Post", new {postId = post.PostId})">Подробнее</a>

                <div class="right">
                    <label class="view-count">@post.ViewCount просмотр(ов)</label>
                    <i class="added-time">(@post.CreationDate.ToShortDateString())</i>
                </div>
            </div>
        </div>
    }
}

@Html.Action("Pager", "Element", 
    new { action = "Index", controller = "PostPreviews", currentPageIndex = Model.CurrentPage, pageCount = Model.PageCount})

<script>
    $(function () {
        $("#notes-ref").addClass("selected");
    });
</script>

PersonalBlog/Views/Shared/_AdminLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/css/adminLayout")

<header>
    <a id="posts" href="@Url.Action("Posts", "Admin", new { pageIndex = 1 })">Посты</a>
    <a id="logs" href="@Url.Action("Logs", "Admin", new { pageIndex = 1 })">Логи</a>
</header>
<div class="admin-body">
    @RenderBody()
</div>

PersonalBlog/Views/Shared/_BlogLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/css/blog")

<!--We can just add link and use emoji without downloading all images and .css file-->
<link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">

<header>
    <a class="nick" href="@Url.Action("Index", "Home")">80LevelElf about IT</a>
    <a id="notes-ref" href="@Url.Action("Index", "PostPreviews", new { pageIndex = 1 })">Записи</a>
    <a id="my-projects_ref" href="@Url.Action("Index", "MyProjects")">Мои проекты</a>
    <a id="about-me-ref" href="@Url.Action("Index", "AboutMe")">Обо мне</a>
</header>

<div class="content-div">
    @RenderBody()
</div>

<footer>
    <label>Салахутдинов Рустам (2016 - @DateTime.Now.Year)</label>
</footer>

<!--For Google Analytics-->
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-84262017-1', 'auto');
    ga('send', 'pageview');

</script>

PersonalBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru-ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css",
        "~/Content/themes/base/css")
    <link rel="shortcut icon" type="image/ico" href="/favicon.ico">
</head>
<body>
    @Scripts.Render("~/bundles/jquery",
        "~/bundles/jqueryui",
        "~/bundles/utils")

    @RenderBody()
</body>
</html>